### ISSUE TITLE
Rule of hooks error on useColorScheme v2.0.3

### ISSUE THREAD

**Issue by Kyle772** [FrontFin/mesh-react-native-sdk#27]
Wanted to drop this off for you guys on the RN sdk

### Cause
I'm getting an error on the line within the RN sdk (2.0.3) On file SDKContainer.styled.js useColorScheme is throwing a rule of hooks error. Looking at the type file and the source file useColorScheme doesn't look like it exists anymore? Maybe the types are out of sync on this version? 

Not sure but I updated the line in SDKContainer.styled.js to 
`export const isDarkMode = false;`
from 
`export const isDarkMode = useColorScheme ? useColorScheme() === 'dark' : false;`
and I'm no longer seeing the error

### Diff
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@meshconnect/react-native-link-sdk/lib/components/SDKContainer.styled.js b/node_modules/@meshconnect/react-native-link-sdk/lib/components/SDKContainer.styled.js
index a04d3f1..ebdd86e 100644
--- a/node_modules/@meshconnect/react-native-link-sdk/lib/components/SDKContainer.styled.js
+++ b/node_modules/@meshconnect/react-native-link-sdk/lib/components/SDKContainer.styled.js
@@ -26,7 +26,7 @@ export const styles = StyleSheet.create({
         resizeMode: 'contain',
     },
 });
-export const isDarkMode = useColorScheme ? useColorScheme() === 'dark' : false;
+export const isDarkMode = true;
 export const statusBarStyle = {
     backgroundColor: isDarkMode ? '#000000' : '#ffffff',
 };
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by afzalahmad-front** [comment]
This issue is resolved.
